---
stages:
  - test

.run_tests: &run_tests
  image: registry.merchise.org/mercurio/odoo-docker:o${ODOO_VERSION}-${PYTHON_VERSION}
  services:
    - name: "mdillon/postgis:10-alpine"
      alias: "postgres"
  stage: test
  tags:
    - gitlab.merchise.org
  script:
    - |
      set -x
      pip install -U wheel setuptools
      pip install "futures<3"
      pip install -r requirements.txt
      pip install -U "six>=1.9.0" "decorator>=4.0,<4.2" "hypothesis>=3.24"
      pip install -e .
      STDOUT=/tmp/odoo.log
      ADDONS=$(find -L addons/ odoo/addons/ -type f -name '__manifest__.py' | while read f; do dirname $f; done | while read d; do basename $d; done | sort -u | egrep -v '^(hw_|l10n_|theme_|auth_ldap$|document_ftp$|base_gengo$|website_gengo$|website_instantclick$|pad$|pad_project$|project_gantt$|note_pad$|pos_cache$|pos_blackbox_be$|test_performance$|google_calendar$)' | xargs | tr " " ",")
      ./odoo-bin -d odoodb --db_host=postgres --db_user=odoodb -i base,$ADDONS --stop-after-init --test-enable --log-level=test --workers=0 --max-cron-threads=0 2>&1 | tee $STDOUT
      ! egrep "(At least one test failed when loading the modules.|(ERROR|CRITICAL) odoodb)" $STDOUT


run all tests in MRs:
  <<: *run_tests
  variables:
    POSTGRES_USER: odoodb
    PYTHON_VERSION: "3.8"
    ODOO_VERSION: "12"
    GIT_DEPTH: "2"
  only:
    - merge_request
