stages:
  - test

.run_tests: &run_tests
  image: python:${PYTHON_VERSION}-${DEBIAN_VERSION}
  services:
    - name: "mdillon/postgis:10-alpine"
      alias: "postgres"
  stage: test
  cache:
    paths:
      - .cache/
    key: "$CI_JOB_NAME"
  script:
    - |
      set -x
      apt-get update
      apt-get install -y --no-install-recommends chromium libsasl2-dev python-dev libldap2-dev libssl-dev postgresql-client
      export PIP_CACHE_DIR=.cache/pip
      export PIP_DISABLE_PIP_VERSION_CHECK=1
      pip install -r requirements.txt
      pip install -e .
      pip install websocket-client "ipython<6" ipdb "hypothesis>=3.24" "phonenumbers~=8.12"
      STDOUT=/tmp/odoo.log
      ADDONS=$(find -L addons/ odoo/addons/ -type f -name '__manifest__.py' | while read f; do dirname $f; done | while read d; do basename $d; done | sort -u | egrep -v '^(payment|hw_|l10n_|theme_|auth_ldap$|document_ftp$|base_gengo$|website_gengo$|website_instantclick$|pad$|pad_project$|project_gantt$|note_pad$|pos_cache$|pos_blackbox_be$|test_performance$|google_calendar$)' | xargs | tr " " ",")
      ./odoo-bin -d odoodb --db_host=postgres --db_user=odoodb -i base,$ADDONS --stop-after-init --test-enable --log-level=test --workers=0 --max-cron-threads=0 2>&1 | tee $STDOUT
      ! egrep "(At least one test failed when loading the modules.|(ERROR|CRITICAL) odoodb)" $STDOUT


run all tests in MRs (Python 3.8):
  <<: *run_tests
  variables:
    POSTGRES_USER: odoodb
    PYTHON_VERSION: "3.8"
    DEBIAN_VERSION: "buster"
    GIT_DEPTH: "2"
  only:
    - merge_request

run all tests in MRs (Python 3.9):
  <<: *run_tests
  variables:
    POSTGRES_USER: odoodb
    PYTHON_VERSION: "3.9"
    DEBIAN_VERSION: "buster"
    GIT_DEPTH: "2"
  only:
    - merge_request
  allow_failure: true
